# Generated by Django 3.2.8 on 2021-10-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('user_type', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], max_length=300)),
            ],
        ),
    ]
