# Generated by Django 3.2.8 on 2021-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servic_type', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('phone_num', models.CharField(max_length=300)),
                ('car_name', models.CharField(max_length=300)),
                ('cartime', models.CharField(max_length=300)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
    ]
